name: 'Cleanup ghcr container versions'
description: 'Keeps only the latest version of a container package on Github Container Registry (ghcr.io)'
branding:
  icon: 'x'
  color: 'gray-dark'
inputs:
  access-token:
    description: 'Access token'
    required: true
  package-name: 
    description: 'Name of the package to clean up'
    required: true
  versions-to-keep:
    description: 'How many versions should be kept, decending by creation date'
    required: false
    default: 1
runs:
  using: 'node12'
  main: 'index.js'